### ISSUE TITLE
Bad typesetted math

### ISSUE THREAD

**Issue by Atcold** [decisionforce/pgdrive-generalization-paper#4]
There's something wrong with your LaTeX distribution.
All the math doesn't look properly formatted.
![image](https://user-images.githubusercontent.com/2119355/110020056-1ec62300-7cf7-11eb-8465-aee5c1ce653c.png)
You need to use `$` around the math in order to have it correctly rendered.

**Comment by pengzhenghao** [comment]
Hi @Atcold ! Thanks for suggestions! However, we do follow the standard latex way to write math equations and use `pdfLaTex` to typeset the file. I guess what the format problem you refer to is that the equation has same style as body. I guess this is because the style file we use in this pdf (ICRA template). In fact, when using other template, the math looks better!

**Comment by pengzhenghao** [comment]
A note for potential reader:

We use a bad package accidentally:
```latex
 \usepackage{mathastext}
```
so the math is in bad typeset.

Disabling the package makes thing work! We are sorry for blaming ICRA template for this issue.

**Comment by Atcold** [comment]
Cool, I'm glad this was solved. 😃
